# Numpy 

In [1]:
import numpy as np

# One dimensional array

In [2]:
a=np.array([1,2,3,4],dtype='int16')
print(a)
a.ndim
a.shape

[1 2 3 4]


(4,)

# 2D array

In [3]:
b=np.array([[1.0,2.0,3.0],[5.0,6.0,7.0]])
print(b)
b.ndim
# b.shape

[[1. 2. 3.]
 [5. 6. 7.]]


2

In [4]:
c=np.array([1,2,3])
d=np.array([5,6,7]) #can't multiply sequence by non-int of type 'list'. Have to put np.array first

print(c*d)

[ 5 12 21]


# Get Dimension

In [5]:
x = np.array([1, 2, 3])
x.ndim



1

In [6]:
y= np.array([[1,2,3],
            [4,5,6]])
y.ndim


2

In [7]:
y.shape #printing 2 rows and 3 columns

(2, 3)

In [8]:
y.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

# Get Size

In [10]:
a.itemsize

2

In [11]:
b.itemsize

8

# Get Specific Element (r,c)

In [12]:
r=np.array([[1,2,3,4],[11,12,13,14]])
print(r)

[[ 1  2  3  4]
 [11 12 13 14]]


In [13]:
r[1,2] #or [1,-2] will give te same result

13

# Getting a specific row 

In [14]:
a1=np.array([[11,12,13,14],[21,22,23,24]])
print(a1)

[[11 12 13 14]
 [21 22 23 24]]


In [15]:
a1[0,:]

array([11, 12, 13, 14])

# Getting a specific column

In [16]:
a1[:,1]

array([12, 22])

# (Slicing)Getting Specific elements from row and column

In [17]:
a1[1,1:3:1] #taking 2nd row # for 2D array it means 1stelement,2ndelement,step and for 3D arr it means outer bigger array then smaller inner array

array([22, 23])

In [18]:
a1[0,1:3:1] #a1[0,1:-1:1] same

array([12, 13])

In [19]:
a1[0:2:1,0] #taking 1st column

array([11, 21])

In [20]:
a1[1,2]=32
print(a1)

[[11 12 13 14]
 [21 22 32 24]]


# Changing all elements of a specific column and row

In [21]:
a1[:,1]=5
print(a1)

[[11  5 13 14]
 [21  5 32 24]]


In [22]:
a1[1,:]=2 #row
print(a1)

[[11  5 13 14]
 [ 2  2  2  2]]


# Changing two different elements to 2 different values of a specific column and row

In [23]:
a1[1,:]=[1,2,3,4]
print(a1)

[[11  5 13 14]
 [ 1  2  3  4]]


In [24]:
a1[:,0]=[98,99]
print(a1)

[[98  5 13 14]
 [99  2  3  4]]


# 3D array

In [25]:
#..............big r1.........bigr2........
#...........smallr1..smallr2..smallr1..smallr2....
b1=np.array([[[1,2],[3,4]],[[41,42],[43,44]]])
print(b1)

[[[ 1  2]
  [ 3  4]]

 [[41 42]
  [43 44]]]


# Get specific element from a 3D array

In [26]:
#work outside in
#1st take the bigger row, then consider the inner element
b1[1,0,1]


42

In [27]:
b1[:,1,0:2] #all elements of bigger matrix, 2nd row, all column


array([[ 3,  4],
       [43, 44]])

In [28]:
b1[:,0:2,0] #all elements of bigger matrix:all rows: 1st column

array([[ 1,  3],
       [41, 43]])

# Initializing 0s

In [29]:
np.zeros((2,3,5,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [30]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

# Random numbers

In [31]:
np.random.rand(4,2)

array([[0.70133177, 0.78761577],
       [0.07623637, 0.94643859],
       [0.95715981, 0.26159572],
       [0.74126404, 0.38651682]])

In [32]:
np.random.randint(-4,2,size=(3,2))

array([[-3,  0],
       [-2, -2],
       [ 0, -4]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
a2=np.array([[1,2,3,5,6]])
arr=np.repeat(a2,2,axis=0)
print(arr)

[[1 2 3 5 6]
 [1 2 3 5 6]]


In [35]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [37]:
output[1:4,1:4]=z #taking elements from 2nd row to 3rd row and 2nd column to 3rd column
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying Array

In [38]:
a3=np.array([10,14,15,18])
b3=a3
b3[0]=90
print(b3)
print(a3) #changing b3 also changes the value of the 1st element of a3

[90 14 15 18]
[90 14 15 18]


In [39]:
#use copy()
a3=np.array([10,14,15,18])
b3=a3.copy()
b3[0]=90
print(b3)
print(a3) #changing b3 won't changes the value of the 1st element of a3

[90 14 15 18]
[10 14 15 18]


# Statistics

In [40]:
stat=np.array([[1,2,3,4],[5,6,7,8]])
print(stat)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
np.average(stat, axis=1)

array([2.5, 6.5])

In [42]:
np.min(stat)

1

In [43]:
np.max(stat,axis=1) #without axis the output is 8

array([4, 8])

In [44]:
np.sum(stat,axis=0) ##without axis the output is 36

array([ 6,  8, 10, 12])

# Reshaping Arrays

In [45]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [46]:
after=before.reshape(4,2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:
b4=np.array([[[1,2,3,21],[4,5,6,22],[13,14,15,23]],[[7,8,9,24],[10,11,12,25],[16,17,18,26]]])
print(b4) 
b4.shape #bigger outer array,then row of inner array,then col of inner arr

[[[ 1  2  3 21]
  [ 4  5  6 22]
  [13 14 15 23]]

 [[ 7  8  9 24]
  [10 11 12 25]
  [16 17 18 26]]]


(2, 3, 4)

In [48]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v2,v1,v2,v1])

array([[5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

# Horizontal stack

In [49]:
h1=np.ones([2,4])
h2=np.zeros([2,2]) #rows has to match exactly
h1


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
h2

array([[0., 0.],
       [0., 0.]])

In [51]:
np.hstack([h1,h2]) #all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [52]:
np.hstack([h2,h1])

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

# Load data using numpy instead of pandas

In [53]:
file_data=np.genfromtxt('np.txt',delimiter=',') #by default it casts data into float type
file_data

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [54]:
file_data.astype('int32')#casting into intiger

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int32)

# Boolean Masking and Advanced Indexing

In [55]:
file_data>50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [56]:
file_data[file_data>8].astype('int32')

array([ 9, 10, 11, 12, 13, 14, 15], dtype=int32)

# Index with list in numpy

In [57]:
a5=np.array([1,2,3,4,5,6,7,8,9]) #one dimension
a5[[2,3,7]]

array([3, 4, 8])

In [58]:
a6=np.array([[1,2,3],[4,5,6]]) #two dimension
a6[[1],[2]]

array([6])

In [59]:
a6[[0]]

array([[1, 2, 3]])

In [60]:
((file_data>8)&(file_data<20))

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [66]:
file_data[((file_data>8)&(file_data<20))].astype('int32')

array([ 9, 10, 11, 12, 13, 14, 15], dtype=int32)

# Advanced Slicing

In [67]:
d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [71]:
d[2:4,1:3] #putting coma denotes the first one as row and second one as column and ":" denotes the elements

array([[10, 11],
       [14, 15]])

In [72]:
d[[2,4],[0,2]]

array([ 9, 19])